In [2]:
from awpy import Demo

In [10]:
dem = Demo(path="thunderpick-world-championship-2025-furia-vs-natus-vincere-bo5-at4WC5_0tYAwimngCtYokc/furia-vs-natus-vincere-m1-mirage.dem", verbose=True)
dem.parse()

print(f"\nHeader: \n{dem.header}")
print(f"\nRounds: \n{dem.rounds.head(n=3)}")
print(f"\nKills: \n{dem.kills.head(n=3)}")
print(f"\nDamages: \n{dem.damages.head(n=3)}")
print(f"\nWeapon Fires: \n{dem.shots.head(n=3)}")
print(f"\nBomb: \n{dem.bomb.head(n=3)}")
print(f"\nSmokes: \n{dem.smokes.head(n=3)}")
print(f"\nInfernos: \n{dem.infernos.head(n=3)}")
print(f"\nGrenades: \n{dem.grenades.head(n=3)}")
print(f"\nFootsteps: \n{dem.footsteps.head(n=3)}")
print(f"\nTicks: \n{dem.ticks.head(n=3)}")

2026-01-12 04:00:00.249 | DEBUG    | awpy.demo:parse:220 - Starting to parse thunderpick-world-championship-2025-furia-vs-natus-vincere-bo5-at4WC5_0tYAwimngCtYokc/furia-vs-natus-vincere-m1-mirage.dem
2026-01-12 04:00:19.749 | SUCCESS  | awpy.demo:parse:271 - Finished parsing thunderpick-world-championship-2025-furia-vs-natus-vincere-bo5-at4WC5_0tYAwimngCtYokc/furia-vs-natus-vincere-m1-mirage.dem, took 19.50 seconds

Header:
{'demo_version_guid': '8e9d71ab-04a1-4c01-bb61-acfede27c046', 'allow_clientside_entities': True, 'demo_version_name': 'valve_demo_2', 'demo_file_stamp': 'PBDEMS2\x00', 'client_name': 'SourceTV Demo', 'allow_clientside_particles': True, 'addons': '', 'patch_version': '14112', 'fullpackets_version': '2', 'game_directory': '/home/cs2serwer/steamcmd/cs2-ds/game/csgo', 'server_name': 'eBot :: Furia vs NaVi', 'map_name': 'de_mirage'}

Rounds:
shape: (3, 9)
┌───────────┬───────┬───────┬──────────────┬───┬────────┬───────────────┬────────────┬────────────┐
│ round_num ┆ start ┆ end   ┆ official_end ┆ … ┆ winner ┆ reason        ┆ bomb_plant ┆ bomb_site  │
│ ---       ┆ ---   ┆ ---   ┆ ---          ┆   ┆ ---    ┆ ---           ┆ ---        ┆ ---        │
│ u32       ┆ i32   ┆ i32   ┆ i32          ┆   ┆ str    ┆ str           ┆ i64        ┆ str        │
╞═══════════╪═══════╪═══════╪══════════════╪═══╪════════╪═══════════════╪════════════╪════════════╡
│ 1         ┆ 1     ┆ 6474  ┆ 6794         ┆ … ┆ t      ┆ ct_killed     ┆ 5628       ┆ bombsite_b │
│ 2         ┆ 6794  ┆ 14117 ┆ 14437        ┆ … ┆ t      ┆ ct_killed     ┆ 13014      ┆ bombsite_b │
│ 3         ┆ 14437 ┆ 24663 ┆ 24983        ┆ … ┆ t      ┆ bomb_exploded ┆ 22039      ┆ bombsite_b │
└───────────┴───────┴───────┴──────────────┴───┴────────┴───────────────┴────────────┴────────────┘

Kills:
shape: (3, 47)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ assistedfl ┆ assister_X ┆ assister_Y ┆ assister_Z ┆ … ┆ weapon_it ┆ weapon_or ┆ wipe ┆ round_num │
│ ash        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ emid      ┆ iginalown ┆ ---  ┆ ---       │
│ ---        ┆ f32        ┆ f32        ┆ f32        ┆   ┆ ---       ┆ er_xuid   ┆ i32  ┆ u32       │
│ bool       ┆            ┆            ┆            ┆   ┆ str       ┆ ---       ┆      ┆           │
│            ┆            ┆            ┆            ┆   ┆           ┆ str       ┆      ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 228786491 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆            ┆            ┆   ┆ 52        ┆           ┆      ┆           │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 416758373 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆            ┆            ┆   ┆ 76        ┆           ┆      ┆           │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 416758373 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆            ┆            ┆   ┆ 76        ┆           ┆      ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

Damages:
shape: (3, 27)
┌───────┬────────────┬────────────┬────────────┬───┬────────────┬─────────┬────────────┬───────────┐
│ armor ┆ attacker_X ┆ attacker_Y ┆ attacker_Z ┆ … ┆ victim_sid ┆ weapon  ┆ dmg_health ┆ round_num │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ e          ┆ ---     ┆ _real      ┆ ---       │
│ i32   ┆ f32        ┆ f32        ┆ f32        ┆   ┆ ---        ┆ str     ┆ ---        ┆ u32       │
│       ┆            ┆            ┆            ┆   ┆ str        ┆         ┆ i32        ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪════════════╪═════════╪════════════╪═══════════╡
│ 0     ┆ -434.11230 ┆ -774.91485 ┆ -259.27337 ┆ … ┆ t          ┆ hkp2000 ┆ 100        ┆ 1         │
│       ┆ 5          ┆ 6          ┆ 6          ┆   ┆            ┆         ┆            ┆           │
│ 94    ┆ -821.28076 ┆ -440.59045 ┆ -166.45623 ┆ … ┆ t          ┆ hkp2000 ┆ 14         ┆ 1         │
│       ┆ 2          ┆ 4          ┆ 8          ┆   ┆            ┆         ┆            ┆           │
│ 85    ┆ -944.72229 ┆ 288.631836 ┆ -167.69885 ┆ … ┆ t          ┆ hkp2000 ┆ 19         ┆ 1         │
│       ┆            ┆            ┆ 3          ┆   ┆            ┆         ┆            ┆           │
└───────┴────────────┴────────────┴────────────┴───┴────────────┴─────────┴────────────┴───────────┘

Weapon Fires:
shape: (3, 14)
┌─────────┬──────────┬────────┬──────┬───┬───────────────┬─────────────┬───────────────┬───────────┐
│ ct_side ┆ silenced ┆ t_side ┆ tick ┆ … ┆ player_steami ┆ player_side ┆ weapon        ┆ round_num │
│ ---     ┆ ---      ┆ ---    ┆ ---  ┆   ┆ d             ┆ ---         ┆ ---           ┆ ---       │
│ str     ┆ bool     ┆ str    ┆ i32  ┆   ┆ ---           ┆ str         ┆ str           ┆ u32       │
│         ┆          ┆        ┆      ┆   ┆ u64           ┆             ┆               ┆           │
╞═════════╪══════════╪════════╪══════╪═══╪═══════════════╪═════════════╪═══════════════╪═══════════╡
│ ct      ┆ false    ┆ t      ┆ 21   ┆ … ┆ 7656119906306 ┆ t           ┆ weapon_smokeg ┆ 1         │
│         ┆          ┆        ┆      ┆   ┆ 8840          ┆             ┆ renade        ┆           │
│ ct      ┆ false    ┆ t      ┆ 27   ┆ … ┆ 7656119796069 ┆ ct          ┆ weapon_knife_ ┆ 1         │
│         ┆          ┆        ┆      ┆   ┆ 0195          ┆             ┆ butterfly     ┆           │
│ ct      ┆ false    ┆ t      ┆ 259  ┆ … ┆ 7656119813440 ┆ ct          ┆ weapon_knife_ ┆ 1         │
│         ┆          ┆        ┆      ┆   ┆ 1925          ┆             ┆ m9_bayonet    ┆           │
└─────────┴──────────┴────────┴──────┴───┴───────────────┴─────────────┴───────────────┴───────────┘

Bomb:
shape: (3, 9)
┌──────┬────────┬──────────────┬─────────────┬───┬───────────────┬─────────┬───────────┬───────────┐
│ tick ┆ event  ┆ X            ┆ Y           ┆ … ┆ steamid       ┆ name    ┆ bombsite  ┆ round_num │
│ ---  ┆ ---    ┆ ---          ┆ ---         ┆   ┆ ---           ┆ ---     ┆ ---       ┆ ---       │
│ i32  ┆ str    ┆ f32          ┆ f32         ┆   ┆ u64           ┆ str     ┆ str       ┆ u32       │
╞══════╪════════╪══════════════╪═════════════╪═══╪═══════════════╪═════════╪═══════════╪═══════════╡
│ 5628 ┆ plant  ┆ -1969.0625   ┆ 450.034454  ┆ … ┆ 7656119907618 ┆ makazze ┆ BombsiteB ┆ 1         │
│      ┆        ┆              ┆             ┆   ┆ 9612          ┆         ┆           ┆           │
│ 6794 ┆ pickup ┆ -1839.998535 ┆ -518.556152 ┆ … ┆ 7656119805025 ┆ iM      ┆ null      ┆ 2         │
│      ┆        ┆              ┆             ┆   ┆ 0233          ┆         ┆           ┆           │
│ 7297 ┆ drop   ┆ 1216.0       ┆ -115.0      ┆ … ┆ 7656119805025 ┆ iM      ┆ null      ┆ 2         │
│      ┆        ┆              ┆             ┆   ┆ 0233          ┆         ┆           ┆           │
└──────┴────────┴──────────────┴─────────────┴───┴───────────────┴─────────┴───────────┴───────────┘

Smokes:
shape: (3, 15)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ entity_id ┆ start_tic ┆ end_tick ┆ thrower_X ┆ … ┆ X         ┆ Y         ┆ Z         ┆ round_num │
│ ---       ┆ k         ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆ ---       ┆ i64      ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ u32       │
│           ┆ i64       ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 192       ┆ 525       ┆ 1937     ┆ 338.36767 ┆ … ┆ -1209.249 ┆ -653.3668 ┆ -165.9687 ┆ 1         │
│           ┆           ┆          ┆ 6         ┆   ┆ 023       ┆ 82        ┆ 5         ┆           │
│ 295       ┆ 1048      ┆ 2460     ┆ -1952.162 ┆ … ┆ -1351.019 ┆ 756.60754 ┆ -77.96875 ┆ 1         │
│           ┆           ┆          ┆ 231       ┆   ┆ 897       ┆ 4         ┆           ┆           │
│ 253       ┆ 3689      ┆ 5101     ┆ 220.41943 ┆ … ┆ -636.3620 ┆ -899.5399 ┆ -245.9687 ┆ 1         │
│           ┆           ┆          ┆ 4         ┆   ┆ 61        ┆ 17        ┆ 5         ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Infernos:
shape: (3, 15)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ entity_id ┆ start_tic ┆ end_tick ┆ thrower_X ┆ … ┆ X         ┆ Y         ┆ Z         ┆ round_num │
│ ---       ┆ k         ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆ ---       ┆ i64      ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ u32       │
│           ┆ i64       ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 320       ┆ 3818      ┆ 4267     ┆ 50.346844 ┆ … ┆ -1184.093 ┆ -604.7418 ┆ -165.9687 ┆ 1         │
│           ┆           ┆          ┆           ┆   ┆ 994       ┆ 21        ┆ 5         ┆           │
│ 478       ┆ 11664     ┆ 12113    ┆ 820.82580 ┆ … ┆ 70.106339 ┆ -2102.155 ┆ -35.96875 ┆ 2         │
│           ┆           ┆          ┆ 6         ┆   ┆           ┆ 518       ┆           ┆           │
│ 112       ┆ 16103     ┆ 16455    ┆ -675.7697 ┆ … ┆ 412.73895 ┆ -1543.832 ┆ -232.0    ┆ 3         │
│           ┆           ┆          ┆ 14        ┆   ┆ 3         ┆ 031       ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Grenades:
shape: (3, 9)
┌───────────────────┬───────────┬───────────────┬──────┬───┬──────┬──────┬───────────┬───────────┐
│ thrower_steamid   ┆ thrower   ┆ grenade_type  ┆ tick ┆ … ┆ Y    ┆ Z    ┆ entity_id ┆ round_num │
│ ---               ┆ ---       ┆ ---           ┆ ---  ┆   ┆ ---  ┆ ---  ┆ ---       ┆ ---       │
│ u64               ┆ str       ┆ str           ┆ i32  ┆   ┆ f32  ┆ f32  ┆ i32       ┆ u32       │
╞═══════════════════╪═══════════╪═══════════════╪══════╪═══╪══════╪══════╪═══════════╪═══════════╡
│ 76561197960690195 ┆ FalleN    ┆ CSmokeGrenade ┆ 1    ┆ … ┆ null ┆ null ┆ 161       ┆ 1         │
│ 76561199063068840 ┆ w0nderful ┆ CSmokeGrenade ┆ 1    ┆ … ┆ null ┆ null ┆ 163       ┆ 1         │
│ 76561198013243326 ┆ Aleksib   ┆ CSmokeGrenade ┆ 1    ┆ … ┆ null ┆ null ┆ 212       ┆ 1         │
└───────────────────┴───────────┴───────────────┴──────┴───┴──────┴──────┴───────────┴───────────┘

Footsteps:
shape: (3, 15)
┌─────────┬──────────┬────────┬───────┬───┬─────────────┬────────────────┬─────────────┬───────────┐
│ ct_side ┆ duration ┆ radius ┆ step  ┆ … ┆ player_name ┆ player_steamid ┆ player_side ┆ round_num │
│ ---     ┆ ---      ┆ ---    ┆ ---   ┆   ┆ ---         ┆ ---            ┆ ---         ┆ ---       │
│ str     ┆ f32      ┆ i32    ┆ bool  ┆   ┆ str         ┆ u64            ┆ str         ┆ u32       │
╞═════════╪══════════╪════════╪═══════╪═══╪═════════════╪════════════════╪═════════════╪═══════════╡
│ ct      ┆ 0.1      ┆ 98     ┆ false ┆ … ┆ w0nderful   ┆ 76561199063068 ┆ t           ┆ 1         │
│         ┆          ┆        ┆       ┆   ┆             ┆ 840            ┆             ┆           │
│ ct      ┆ 0.1      ┆ 800    ┆ false ┆ … ┆ w0nderful   ┆ 76561199063068 ┆ t           ┆ 1         │
│         ┆          ┆        ┆       ┆   ┆             ┆ 840            ┆             ┆           │
│ ct      ┆ 0.5      ┆ 1100   ┆ true  ┆ … ┆ b1t         ┆ 76561198246607 ┆ t           ┆ 1         │
│         ┆          ┆        ┆       ┆   ┆             ┆ 476            ┆             ┆           │
└─────────┴──────────┴────────┴───────┴───┴─────────────┴────────────────┴─────────────┴───────────┘

Ticks:
shape: (3, 10)
┌────────┬─────────┬──────┬──────────────┬───┬──────┬───────────────────┬──────────┬───────────┐
│ health ┆ place   ┆ side ┆ X            ┆ … ┆ tick ┆ steamid           ┆ name     ┆ round_num │
│ ---    ┆ ---     ┆ ---  ┆ ---          ┆   ┆ ---  ┆ ---               ┆ ---      ┆ ---       │
│ i32    ┆ str     ┆ str  ┆ f32          ┆   ┆ i32  ┆ u64               ┆ str      ┆ u32       │
╞════════╪═════════╪══════╪══════════════╪═══╪══════╪═══════════════════╪══════════╪═══════════╡
│ 100    ┆ CTSpawn ┆ ct   ┆ -1775.537598 ┆ … ┆ 1    ┆ 76561198200982290 ┆ molodoy  ┆ 1         │
│ 100    ┆ CTSpawn ┆ ct   ┆ -1655.647583 ┆ … ┆ 1    ┆ 76561198134401925 ┆ YEKINDAR ┆ 1         │
│ 100    ┆ CTSpawn ┆ ct   ┆ -1719.200317 ┆ … ┆ 1    ┆ 76561198058500492 ┆ KSCERATO ┆ 1         │
└────────┴─────────┴──────┴──────────────┴───┴──────┴───────────────────┴──────────┴───────────┘

In [11]:
print(f"\nTicks: \n{dem.ticks.head(n=3)}")

Ticks:
shape: (3, 10)
┌────────┬─────────┬──────┬──────────────┬───┬──────┬───────────────────┬──────────┬───────────┐
│ health ┆ place   ┆ side ┆ X            ┆ … ┆ tick ┆ steamid           ┆ name     ┆ round_num │
│ ---    ┆ ---     ┆ ---  ┆ ---          ┆   ┆ ---  ┆ ---               ┆ ---      ┆ ---       │
│ i32    ┆ str     ┆ str  ┆ f32          ┆   ┆ i32  ┆ u64               ┆ str      ┆ u32       │
╞════════╪═════════╪══════╪══════════════╪═══╪══════╪═══════════════════╪══════════╪═══════════╡
│ 100    ┆ CTSpawn ┆ ct   ┆ -1775.537598 ┆ … ┆ 1    ┆ 76561198200982290 ┆ molodoy  ┆ 1         │
│ 100    ┆ CTSpawn ┆ ct   ┆ -1655.647583 ┆ … ┆ 1    ┆ 76561198134401925 ┆ YEKINDAR ┆ 1         │
│ 100    ┆ CTSpawn ┆ ct   ┆ -1719.200317 ┆ … ┆ 1    ┆ 76561198058500492 ┆ KSCERATO ┆ 1         │
└────────┴─────────┴──────┴──────────────┴───┴──────┴───────────────────┴──────────┴───────────┘

In [12]:
for event_name, event in dem.events.items():
    print(f"{event_name}: {event.shape[0]} rows x {event.shape[1]} columns")

smokegrenade_expired: 133 rows x 15 columns
round_officially_ended: 18 rows x 4 columns
inferno_expire: 95 rows x 15 columns
bomb_defused: 2 rows x 12 columns
smokegrenade_detonate: 137 rows x 15 columns
hegrenade_detonate: 50 rows x 15 columns
player_spawn: 180 rows x 11 columns
bomb_pickup: 63 rows x 11 columns
weapon_fire: 2864 rows x 13 columns
player_hurt: 478 rows x 25 columns
flashbang_detonate: 138 rows x 15 columns
bomb_planted: 15 rows x 12 columns
round_freeze_end: 18 rows x 4 columns
bomb_dropped: 50 rows x 12 columns
item_pickup: 1280 rows x 14 columns
inferno_startburn: 96 rows x 15 columns
player_sound: 16234 rows x 14 columns
player_death: 129 rows x 46 columns
bomb_exploded: 6 rows x 12 columns
round_start: 19 rows x 3 columns
round_end: 19 rows x 5 columns

In [13]:
from awpy.stats import adr

In [15]:
adr(dem)

shape: (30, 6)
┌───────────┬───────────────────┬──────┬──────────┬──────┬────────────┐
│ name      ┆ steamid           ┆ side ┆ n_rounds ┆ dmg  ┆ adr        │
│ ---       ┆ ---               ┆ ---  ┆ ---      ┆ ---  ┆ ---        │
│ str       ┆ u64               ┆ str  ┆ u32      ┆ i32  ┆ f64        │
╞═══════════╪═══════════════════╪══════╪══════════╪══════╪════════════╡
│ molodoy   ┆ 76561198200982290 ┆ t    ┆ 7        ┆ 553  ┆ 79.0       │
│ iM        ┆ 76561198050250233 ┆ ct   ┆ 7        ┆ 823  ┆ 117.571429 │
│ w0nderful ┆ 76561199063068840 ┆ ct   ┆ 7        ┆ 737  ┆ 105.285714 │
│ Aleksib   ┆ 76561198013243326 ┆ ct   ┆ 7        ┆ 212  ┆ 30.285714  │
│ b1t       ┆ 76561198246607476 ┆ ct   ┆ 7        ┆ 648  ┆ 92.571429  │
│ …         ┆ …                 ┆ …    ┆ …        ┆ …    ┆ …          │
│ FalleN    ┆ 76561197960690195 ┆ all  ┆ 19       ┆ 1307 ┆ 68.789474  │
│ molodoy   ┆ 76561198200982290 ┆ all  ┆ 19       ┆ 1047 ┆ 55.105263  │
│ YEKINDAR  ┆ 76561198134401925 ┆ all  ┆ 19       ┆ 733  ┆ 38.578947  │
│ iM        ┆ 76561198050250233 ┆ all  ┆ 19       ┆ 1909 ┆ 100.473684 │
│ b1t       ┆ 76561198246607476 ┆ all  ┆ 19       ┆ 1970 ┆ 103.684211 │
└───────────┴───────────────────┴──────┴──────────┴──────┴────────────┘

In [18]:
from awpy.stats import rating
rating(dem)

shape: (30, 6)
┌───────────┬───────────────────┬──────┬──────────┬──────────┬──────────┐
│ name      ┆ steamid           ┆ side ┆ n_rounds ┆ impact   ┆ rating   │
│ ---       ┆ ---               ┆ ---  ┆ ---      ┆ ---      ┆ ---      │
│ str       ┆ u64               ┆ str  ┆ u32      ┆ f64      ┆ f64      │
╞═══════════╪═══════════════════╪══════╪══════════╪══════════╪══════════╡
│ b1t       ┆ 76561198246607476 ┆ all  ┆ 19       ┆ 1.742105 ┆ 1.530612 │
│ makazze   ┆ 76561199076189612 ┆ all  ┆ 19       ┆ 1.448421 ┆ 1.28075  │
│ molodoy   ┆ 76561198200982290 ┆ all  ┆ 19       ┆ 0.755263 ┆ 0.761201 │
│ iM        ┆ 76561198050250233 ┆ all  ┆ 19       ┆ 1.786316 ┆ 1.740604 │
│ w0nderful ┆ 76561199063068840 ┆ all  ┆ 19       ┆ 1.091579 ┆ 1.159733 │
│ …         ┆ …                 ┆ …    ┆ …        ┆ …        ┆ …        │
│ makazze   ┆ 76561199076189612 ┆ t    ┆ 12       ┆ 1.7175   ┆ 1.524741 │
│ molodoy   ┆ 76561198200982290 ┆ t    ┆ 7        ┆ 1.475714 ┆ 1.105839 │
│ b1t       ┆ 76561198246607476 ┆ t    ┆ 12       ┆ 1.9325   ┆ 1.744939 │
│ w0nderful ┆ 76561199063068840 ┆ t    ┆ 12       ┆ 0.8325   ┆ 1.028561 │
│ Aleksib   ┆ 76561198013243326 ┆ t    ┆ 12       ┆ 0.9375   ┆ 1.097783 │
└───────────┴───────────────────┴──────┴──────────┴──────────┴──────────┘